FROM starefossen/ruby-node

COPY package.json yarn.lock Gemfile* /tmp/
WORKDIR /tmp
RUN yarn
RUN bundle install

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ADD . /usr/src/app
RUN cp -a /tmp/node_modules /usr/src/app/
# vim:ft=dockerfile
